version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nextjs-app
    ports:
      - "3000:3000"
    image: anoopkarnik/turborepo-saas-boilerplate-code-nextjs-app:latest
    restart: always
  
  node-backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.node-backend
    ports:
      - "8020:8020"
    image: anoopkarnik/turborepo-saas-boilerplate-code-node-backend:latest
    restart: always


