version: '3'
services:
  local-db:
    image: pgvector/pgvector:pg17  # or pg15, pg14 — whatever version you want
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5435:5432
    networks:
      - turborepo-network

networks:
  turborepo-network:
    external: true
