version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5440:5432
  redis:
    container_name: redis
    image: "redis:latest"
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"
    restart: always
    networks:
      - turborepo-network
  mongodb:
    container_name: mongodb
    image: "mongodb/mongodb-community-server:latest"
    ports:
      - "27017:27017"
    restart: always
    networks:
      - turborepo-network
networks:
  turborepo-network:
    external: true