frontend:
  label: Frontend
  permalink: /frontend
  description: Frontend tag description

backend:
  label: Backend
  permalink: /backend
  description: Backend tag description

architecture:
  label: Architecture
  permalink: /architecture
  description: Architecture tag description

automation:
  label: Automation
  permalink: /automation
  description: Automation tag description